---
- name: Check SentinelOne Agent Installation on Red Hat-based systems
  hosts: your_redhat_server_group
  become: true
  vars:
    missing_sentinelone_hosts: []  # Initialize an empty list to store missing hosts

  tasks:
    - name: Check if SentinelOne agent is installed
      shell: rpm -q sentinelone  # Replace with the appropriate RPM package name
      register: sentinelone_status
      ignore_errors: true

    - name: Add hostname to list if SentinelOne is not installed
      when: sentinelone_status.rc != 0
      set_fact:
        missing_sentinelone_hosts: "{{ missing_sentinelone_hosts + [inventory_hostname] }}"

  post_tasks:
    - name: Display list of missing hosts
      debug:
        var: missing_sentinelone_hosts